### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hejunbinlan** [lukef/qr.flutter#23] opened 2019-02-01 05:04 UTC
new QrImage(
                  data: 'PDovDRoHAQBUQUEMBwAKQV9RHlOI3MQvVlZWVlZWMQwICldZCgteXgxbXl9fC1cKDFoLXghaDF5bVg8KXVoNMVxeX1deXF5fX11eXFpa',
                  size: 200.0,
                  errorCorrectionLevel: QrErrorCorrectLevel.L,
                )
报错

**Comment by lukef** [comment] 2019-02-09 17:17
I'm not sure what the issue is here so I'm going to close this

**Closed** 2019-02-09 17:17 UTC
